language: 
    - objective-c
os:
    - osx
before_install:
    - brew update
    - brew install homebrew/science/qr_mumps
install: 
    - cp site.template.cfg site.cfg
    - "pip install -r requirements.txt && python setup.py install"
script: python run_tests.py
