from qr_mumps.src.numpy_qr_mumps_INT32_FLOAT64 import NumpyQRMUMPSSolver_INT32_FLOAT64
from qr_mumps.src.qr_mumps_INT32_FLOAT64 import BaseQRMUMPSSolver_INT32_FLOAT64
from qr_mumps.src.qr_mumps_INT32_FLOAT32 import BaseQRMUMPSSolver_INT32_FLOAT32

solver = BaseQRMUMPSSolver_INT32_FLOAT64(2,2,2,True)
print solver
from qr_mumps.src.cysparse_qr_mumps_INT32_FLOAT32 import CySparseQRMUMPSSolver_INT32_FLOAT32
from qr_mumps.src.cysparse_qr_mumps_INT32_FLOAT64 import CySparseQRMUMPSSolver_INT32_FLOAT64
from qr_mumps.src.cysparse_qr_mumps_INT32_COMPLEX64 import CySparseQRMUMPSSolver_INT32_COMPLEX64
from qr_mumps.src.cysparse_qr_mumps_INT32_COMPLEX128 import CySparseQRMUMPSSolver_INT32_COMPLEX128
 
